openapi: 3.0.3
info:
  title: auth resources
  version: '1.0'
paths: {}
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: frank.miller@example.com
          required: true
        password:
          type: string
          example: str0ng
          required: true
    Token:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
