openapi: 3.0.3
info:
  title: comment resources
  version: '1.0'
paths: {}
components:
  schemas:
    CreateCommentRequest:
      type: object
      properties:
        text:
          type: string
          example: title example
          required: true
        rating:
          type: number
          example: 5
          required: true
        offerId:
          type: string
          example: 5
          required: true
    Comment:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea
        text:
          type: string
          example: comment text example
        publishDate:
          type: string
          example: 2024-02-11T18:21:44.746Z
          format: date-time
          description: Дата и время создания элемента (в формате ISO 8601)
        rating:
          type: number
          example: 4
        user:
          $ref: 'user.resources.yml#/components/schemas/User'
