# Offers

## Список предложенией по аренде
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

## Создание предложения по аренде
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Cozy Apartment in the Heart of the City",
  "description": "Experience the charm of city living in this cozy apartment located in the heart of downtown. Close to shops, restaurants, and cultural attractions.",
  "previewImage": "https://picsum.photos/200/200?random=1",
  "images": [
    "https://picsum.photos/400/400?random=1",
    "https://picsum.photos/400/400?random=2",
    "https://picsum.photos/400/400?random=3"
  ],
  "type": "room",
  "bedrooms": 1,
  "maxAdults": 3,
  "price": 1000,
  "features": ["65cab182e3aeca1ef1f2002c", "65cab182e3aeca1ef1f1ff94"],
  "isPremium": true,
  "rating": 3,
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  },
  "cityId": "65cab182e3aeca1ef1f1ff85",
  "userId": "65cab182e3aeca1ef1f1ff79"
}

###

## Получение определенного предложения по аренде
GET http://localhost:4000/offers/65d9bd6ee05bf392c7ae5b6b HTTP/1.1
Content-Type: application/json

###

## Редактирование предложения по аренде
PATCH http://localhost:4000/offers/65d9bd6ee05bf392c7ae5b6b HTTP/1.1
Content-Type: application/json

{
  "title": "Cozy Apartment in the Heart of the City 222",
  "description": "Experience the charm of city living in this cozy apartment located in the heart of downtown. Close to shops, restaurants, and cultural attractions.",
  "previewImage": "https://picsum.photos/200/200?random=1",
  "images": [
    "https://picsum.photos/400/400?random=1",
    "https://picsum.photos/400/400?random=2",
    "https://picsum.photos/400/400?random=3"
  ],
  "type": "room",
  "bedrooms": 1,
  "maxAdults": 3,
  "price": 1000,
  "features": ["65cab182e3aeca1ef1f2002c", "65cab182e3aeca1ef1f1ff94"],
  "isPremium": true,
  "rating": 3,
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  },
  "cityId": "65cab182e3aeca1ef1f1ff85"
}

###

## Удаление предложения по аренде
DELETE http://localhost:4000/offers/65ce3dbc6c51f51be0453eec HTTP/1.1
Content-Type: application/json

###

## Список премиальных предложенией по аренде для города
GET http://localhost:4000/offers/premium?cityId=65cab182e3aeca1ef1f2004d HTTP/1.1
Content-Type: application/json
