
export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  AuthController: Symbol.for('AuthController'),
  AuthService: Symbol.for('AuthService'),
  AuthExceptionFilter: Symbol.for('AuthExceptionFilter'),
  CityService: Symbol.for('CityService'),
  CityModel: Symbol.for('CityModel'),
  FeatureController: Symbol.for('FeatureController'),
  FeatureService: Symbol.for('FeatureService'),
  FeatureModel: Symbol.for('FeatureModel'),
  OfferController: Symbol.for('OfferController'),
  OfferService: Symbol.for('OfferService'),
  OfferModel: Symbol.for('OfferModel'),
  UserController: Symbol.for('UserController'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  CommentController: Symbol.for('CommentController'),
  CommentService: Symbol.for('CommentService'),
  CommentModel: Symbol.for('CommentModel'),
} as const;
